### ISSUE TITLE
Feature in branch texane/pipe

### ISSUE THREAD

**Issue by texane** [texane/stlink#116]
Following a patch from chrisj@rtems.org, I created the branch:
texane/pipe

It does not compile on DEBIAN due to an invalid configure.ac. But it seems the
remaining is ok. The patch needs correction and verification before merging to
master. Anyone doing so is welcome to inform me, so that I can merge.

**Comment by xor-gate** [comment]
This code is very outdated, i tried to understand what it actually does and why we should merge it. This code will not merge to master currently at-all. Any idea what we want to do with this?

**Comment by xor-gate** [comment]
I'm closing this now, as the patch/branch is 4 years old. We can reconsider if it is still needed, and reopen the issue.
