### ISSUE TITLE
Solution for libusb not installed (Ubuntu)

### ISSUE THREAD

**Issue by erkserkserks** [texane/stlink#123]
If you are getting "configure: error: *** Required libusb-1.0 >= 1.0.0 not installed ***" on Ubuntu, then you probably need to install libusb-1.0-0-dev. Stlink does not use libusb-dev. To install the correct version, type "sudo apt-get install libusb-1.0-0-dev"

**Comment by QianFan-Zhao** [comment]
Hello,In my Ubuntu14.04,I try ./configure.but check usb has error:like this:
configure: error: *** Required libusb-1.0 >= 1.0.0 not installed ***

but when i tty to "sudo apt-get install libusb-1.0-0-dev":
The following packages have unmet dependencies:
 libusb-1.0-0-dev : Depends: libusb-1.0-0 (= 2:1.0.6-1) but 2:1.0.17-1ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.

How can i do to resolve this ?
Thanks

**Comment by xor-gate** [comment]
You should install `libusb-1.0-0-dev`.
See https://github.com/texane/stlink/blob/742eba2cd64fdac65275213d2b2773f8a82b5164/.travis.sh#L4
And https://packages.debian.org/sid/libusb-1.0-0-dev
And http://packages.ubuntu.com/xenial/libusb-1.0-0-dev
