### ISSUE TITLE
Semihosting with gcc-arm-embedded

### ISSUE THREAD

**Issue by jhgorse** [texane/stlink#147]
[gcc-arm-embedded](https://answers.launchpad.net/gcc-arm-embedded/) supports semihosting, a feature which allows the target to access the host over the debug link. This can be useful for debugging, but has greater implications for interactive development in general. How can this be done using stlink's st-util debugger?

Here is the sample code path in gcc-arm-embedded toolchain:
gcc-arm-none-eabi-4_7-2013q1/share/gcc-arm-none-eabi/samples/src/semihost
gcc-arm-none-eabi-4_7-2013q1/share/gcc-arm-none-eabi/samples/readme.txt

Here is the succinct readme on the gcc-arm-embedded package for installation and how to use it:
gcc-arm-none-eabi-4_7-2013q1/share/doc/gcc-arm-none-eabi/readme.txt
## Relevant excerpts:

Users can choose to use or not use semihosting by following instructions.
*\* semihosting
You can add -lrdimon in the command line and compile the programs like:
$ arm-none-eabi-gcc --specs=rdimon.specs \
  -Wl,--start-group -lgcc -lc -lc -lm -lrdimon -Wl,--end-group $(OTHER_OPTIONS)

*\* non-semihosting/retarget
If you are using retarget, you can add -lnosys in the command line and compile
the programs like:
$ arm-none-eabi-gcc \
  -Wl,--start-group -lgcc -lc -lc -lm -lnosys -Wl,--end-group $(OTHER_OPTIONS)

May also be relevant to semihosting (see README.nano for further information):
newlib: libc.a libg.a
newlib-nano: libc_s.a libg_s.a with LDFLAGS +=  --specs=nano.specs

---

Resources:
https://answers.launchpad.net/gcc-arm-embedded/+question/212673
https://answers.launchpad.net/gcc-arm-embedded/+question/202914
OpenOCD's contrib/libdcc

**Comment by xor-gate** [comment]
Related to #227

**Comment by Nightwalker-87** [comment]
Old, but still not implemented. IMHO this topic should be discussed again, instead of disappearing in the sink... :-/

**Comment by jhgorse** [comment]
@Nightwalker-87 consider Segger RTT or a clean implementation similar to it rather than semihosting. In RTT there is an up and a down buffer which is read/written asynchronously over the SWD/JTAG debug pipe. It is very fast and less intrusive than semihosting and even some of the ARM ITM/ETM/etc. debug features.

Hope this helps!

Cheers,
Joe

**Comment by Nightwalker-87** [comment]
Thx for the feedback. We have not finally reviewed the current state of implementation of this issue by now. I just came across a reference in the changelog that there has been contribution on this topic. I think we need to clarify the current state first.

**Comment by Nightwalker-87** [comment]
@jhgorse: I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0 for this project? Please verify.

**Comment by jhgorse** [comment]
@Nightwalker-87 I no longer use semihosting, per the comment above. Haven't for about 5 years now. =)

**Comment by Nightwalker-87** [comment]
I understand. Thx for your reply though. Asking @bfoz then or anyone else who is capable to test this. Pointing out other solutions outside of this project may be useful, but obviously do not take this project any further.

**Comment by Nightwalker-87** [comment]
Who can help to verify this? Any volunteers?
