### ISSUE TITLE
Success report for st-link/v2 on STM32F103VET6 HY-STM32_100P

### ISSUE THREAD

**Issue by fourier** [texane/stlink#149]
Flashed and able to debug.

**Comment by 2sheds** [comment]
Поделитесь рецептом, какую схему использовали? Через встроенный PL2303 не работает - использовали второй USB-порт?
Please elaborate on your recipe to make it work with this board. Doesn't work via built-in USB-UART - did you use the second USB port?

**Comment by Nightwalker-87** [comment]
Can anyone verify that this is working?

**Comment by Nightwalker-87** [comment]
@2sheds: Was there a problem with this device on your side?

**Comment by Nightwalker-87** [comment]
The STM32F103VET6 (HY-STM32) board was added to /doc/tested-boards.md in commit c72205661244e8b7711d2299175097cc02cfd7c1. With this board flashing can take place either via USART1 or via USB by making use of the integrated bootloader or via SWD by using a STlink-v2 programmer. The latter is also suitable for debugging.
