### ISSUE TITLE
How to differentiate STM32L1 medium+ from high density devices?

### ISSUE THREAD

**Issue by mitchd** [texane/stlink#152]
I have a project using an STM32L1 high density device.  I've populated the necessary fields in stlink-common.h to communicate with the device.  However, both the medium+ and high density devices share the same chip_id according to the macros in stlink-common

The memory specifications for the medium+ aren't really compatible with the high density device.

A link to my fork with the high density parameters populated:

git://github.com/mitchd/stlink.git

**Comment by Nightwalker-87** [comment]
Does not seem to have been fixed in any stable release so far looking at chipid.h .

**Comment by Nightwalker-87** [comment]
Obviously not fixed in any stable release so far when looking at chipid.h .
