### ISSUE TITLE
STM8 Support

### ISSUE THREAD

**Issue by mahiuchun** [texane/stlink#154]
STM8: http://www.st.com/web/en/catalog/mmc/FM141/SC1244

It may be yet another MCU family that is "inaccessible" from Linux or Mac OS X :(

Fortunately, STM8 shares ST-LINK with STM32. So I guess some of the work here may be reused.

I'm new to STM8 also. And I don't want to be merely a free rider of FOSS. I post this issue hoping that it can raise some interest of STM8 from other people.

**Comment by iDoka** [comment]
+1 for supporting STM8S

**Comment by libertas** [comment]
+10086

**Comment by upost** [comment]
+1 for STM8 support with SWIM.

**Comment by potozi** [comment]
I think [SWIM](http://www.st.com/st-web-ui/static/active/en/resource/technical/document/user_manual/CD00173911.pdf) can be supported, but we need to update firmware for F103 (ST-LINK debugger).

**Comment by xor-gate** [comment]
I think there is not a very high need for STM8. Because nobody seems to gets their hands dirty to integrate the old https://github.com/afaerber/stlink code for STM8 support as most people are using 32-bit controllers. The current structure of the texane/stlink library is not well organised and needs alot of love to actual support both STM8 and STM32.

**Comment by xor-gate** [comment]
As mentioned by the guy who have give a shot to program STM8 has discussed the following:
https://github.com/afaerber/stlink/issues/2#issuecomment-94290520

**Comment by xor-gate** [comment]
As most `texane/stlink` users program STM32 controllers and there is no high need for STM8 I will close this as nobody stands up to integrate/investigate it. The STM8 core is a custom SoC/uC and has nothing todo with the STM32 ARM cores M0/M0+/M3/M4/M7. Most code inside the project is based around the STM32 controllers.

**Comment by andrejsc** [comment]
That's unfortunate... +1

**Comment by iromeo** [comment]
+1 to STM8 support
