### ISSUE TITLE
stlink-gui failed to start

### ISSUE THREAD

**Issue by oco2000** [texane/stlink#158]
stlink-gui failed to start
xubuntu 13.04
libgtk-3 v.3.6.4

Here is the error log:

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_tree_view_set_rules_hint: assertion `GTK_IS_TREE_VIEW (tree_view)' failed

*\* (stlink-gui:10279): CRITICAL **: mem_view_init_headers: assertion `view != NULL' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_tree_view_set_model: assertion `GTK_IS_TREE_VIEW (tree_view)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_tree_view_set_rules_hint: assertion `GTK_IS_TREE_VIEW (tree_view)' failed

*\* (stlink-gui:10279): CRITICAL **: mem_view_init_headers: assertion `view != NULL' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_tree_view_set_model: assertion `GTK_IS_TREE_VIEW (tree_view)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_editable_set_editable: assertion `GTK_IS_EDITABLE (editable)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_show_text: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_info_bar_add_button: assertion `GTK_IS_INFO_BAR (info_bar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_info_bar_get_content_area: assertion `GTK_IS_INFO_BAR (info_bar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_container_add: assertion `GTK_IS_CONTAINER (container)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_show_all: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_statusbar_get_context_id: assertion `GTK_IS_STATUSBAR (statusbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_statusbar_push: assertion `GTK_IS_STATUSBAR (statusbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_drag_dest_set: assertion `GTK_IS_WIDGET (widget)' failed

(stlink-gui:10279): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(stlink-gui:10279): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

(stlink-gui:10279): Gtk-CRITICAL **: gtk_progress_bar_set_fraction: assertion `GTK_IS_PROGRESS_BAR (pbar)' failed

**Comment by Nightwalker-87** [comment]
Problem is solved, but documentation has not been updated as far as I can figure it out.
