### ISSUE TITLE
Does not work with some STM32L1 Medium+ parts

### ISSUE THREAD

**Issue by burnsfisher** [texane/stlink#163]
The code has only STM32L1 device IDs 0x416 and 0x437.  The device on the new Discovery board (STM32L1-DISCO) has ID 0x427.

I do have a patch for this problem.  It shuffles the device names a bit (0x437 is now HIGH, 427 is MEDIUM_PLUS).  I also added a longer timeout for the loader since I kept getting timeout messages despite everything working.

I'm new to working in this environment, so I'll provide the patch when I figure out how it is expected.  Comments welcome, of course.

**Comment by Nightwalker-87** [comment]
Related to #152.

**Comment by Nightwalker-87** [comment]
@burnsfisher: I am doing project maintenance. Which PR was that? Can you have a look? Thx.

**Comment by burnsfisher** [comment]
Looks like PR #165 which you already got.   Thanks for checking!

**Comment by Nightwalker-87** [comment]
Thank you so much for your helpful feedback. :+1:
