### ISSUE TITLE
Can't erase flash after start debugginfg session by st-util.

### ISSUE THREAD

**Issue by ivictbor** [texane/stlink#171]
When I start debugging, code from STM32F10x_StdPeriph_Examples/FLASH/Program/  demo dose not work: bytes are not erased to 0xFF. When I do a pin reset or soft reset, code works. On single power on code also works. When I launch openocd instead of st-util code works without reset. So st-util makes something wrong with STM32 Flash controller. I am using VLDiscovery (f100RB + st-link v1) .

**Comment by xor-gate** [comment]
Old issue, please test with latest stlink. And reopen when similar issue still exists.
