### ISSUE TITLE
STM32F1 load fail

### ISSUE THREAD

**Issue by dimitraPat** [texane/stlink#182]
Hi!
I've found this utility for flashing the STM32 mcu and I think it's very cool.

However, I've been trying to flash the STM32F1 and while at the beginning seems to load correctly, when it reaches add 0x08080000 the flash loader fails.

Does the utility support F1? Do I have to change anything in order to work correctly?

Thanks!

**Comment by xor-gate** [comment]
Feel free to open a new issue when the problem still remains with `v1.2.0` or `master`. Thanks all for your contributions.

**Comment by jonbinney** [comment]
`-v` fixed the problem for me as well... very strange....

**Comment by jsarenik** [comment]
Yes, I remember that behavior. With `-v` it worked, without it needed `-1` to work. I no longer have the HW to try `v1.2.0`.

**Comment by xor-gate** [comment]
@jonbinney do you still need `-v` with `v1.2.0` ?

**Comment by jonbinney** [comment]
I did have this problem yesterday with the current git master version (hash `3f7d0f9df3b1b551ac317b9d3a185c48f19c0c97` )

But today (after a reboot) I can't reproduce the problem at all. It works with or without `-v`. I tried it 5 times and didn't have any problems.

**Comment by xor-gate** [comment]
Probably when adding `-v` printf output takes CPU time and "sleeps" te original code. This seems a timing issue, I have seen an issue with a broken usb cables resulted in super weird behaviour.
