### ISSUE TITLE
Using STM32F4Discovery on 10.9.1

### ISSUE THREAD

**Issue by dscottbuch** [texane/stlink#201]
I'm trying to get an STM32F4Discovery working on a 10.9.1 OS X system.  I've gone through the instruction and have libusb installed and built the STLink utilities, etc. but I'm not getting past step 1, getting the system to see the board.  neither st-util nor openocd will connect.

I'm a noob here.  In loading the kext from this repository I get the following message
>Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        DeviceDriver
        InterfaceDriver
    Kext has no executable or compatible version, so it should not declare any OSBundleLibraries.

>Code Signing Failure: not code signed
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        DeviceDriver
        InterfaceDriver
    Kext has no executable or compatible version, so it should not declare any OSBundleLibraries.

>kext com.libusb.stlink_shield  100009000 is in exception list, allowing to load

I don't think this is actually loading because when I run 
> sudo kextstat | grep st

I don't see the kext loaded.

Any help appreciated.

**Comment by xor-gate** [comment]
You issue is related to #343

**Comment by xor-gate** [comment]
I'm closing this because it is way to old to be usefull, as things have changed in the meanwhile. See also https://github.com/texane/stlink/blob/master/stlinkv1_macosx_driver/README.md. 
Don't hesitate to open a new issue when issue still remains.
