### ISSUE TITLE
Add UNIX man pages

### ISSUE THREAD

**Issue by anatol** [texane/stlink#208]
I found this tool works great on my Linux Arch box. Thanks a lot for it!

One thing that worth improving is to add a UNIX man page. There is already tutorial so having the same information in man file would be very useful.

Thanks.

**Comment by xor-gate** [comment]
This should be in the same category when commandline argument parsing is refactored for milestone 2.0.0. Then we can generate man pages.

**Comment by xor-gate** [comment]
It seems I have broken the build on cmake 2.8. I'm currently using cmake 3.5 so I need to find out on another machine with cmake 2.8. Will fix ASAP on another machine.

**Comment by xor-gate** [comment]
Unix man-pages are merged into `master`.
