### ISSUE TITLE
[compatibility]  libusb-1.0 replaced by libusbx in most distros

### ISSUE THREAD

**Issue by btashton** [texane/stlink#211]
On many new distros libusb-1.0 has been replaced by the maintained libusbx.  As far as stlink is concerned they are drop in compatible, but this might want to be reflected in the readme.

http://libusb.6.n5.nabble.com/libusb-is-dead-long-live-libusbx-td5651413.html

**Comment by xor-gate** [comment]
Probably this is no longer relevant. Reopen when issue stil remains.

**Comment by Nightwalker-87** [comment]
Research reveals: `libusbx` remains present in the following distributions:

- CentOS 7, 8
- Fedora 30, 31, Rawhide
- Slackware 14.1, 14.2, Current

**Comment by Nightwalker-87** [comment]
Commit d2b5f8dbfbb0458e90cde4c90de025e7ae518b7b removes support for `LIBUSBX_API` (deprecated since 2016) and closes this issue.

**Comment by Nightwalker-87** [comment]
Reopening this, as topic is not solved by now.
