### ISSUE TITLE
STM32F4 AHB3 Memory Space

### ISSUE THREAD

**Issue by ghost** [texane/stlink#218]
Hi,
stlink is a great tool, but it does not seem to provide memory regions information for AHB3 peripherals to GDB (it is this tool's responsibility to do so, right?). GDB does not let me to use them, until I manually specify their memory regions with commands:
mem 0x60000000 0x6fffffff rw
mem 0xa0000000 0xa0000fff rw

Sorry, if I am wrong and this has nothing to do with stlink tool.

Thanks.

**Comment by xor-gate** [comment]
I'm closing this in favor of duplicate issue #237.

**Comment by Nightwalker-87** [comment]
@prattmic: Can we be sure about this?

**Comment by Nightwalker-87** [comment]
Fixed in #288.
