### ISSUE TITLE
st-info prints errors before correct output

### ISSUE THREAD

**Issue by cdwilson** [texane/stlink#221]
When I run `st-info` command, I get the following output:
```bash
$ st-info --chipid
Error: could not open stlink device
Error: could not open stlink device
0x0413
$ st-info --descr
Error: could not open stlink device
Error: could not open stlink device
F4 device
$ echo $?
0
```
If I unplug the STM32 from my laptop, I get the following:
```bash
$ st-info --descr
Error: could not open stlink device
Error: could not open stlink device
$ echo $?
255
```
`st-info` seems to be working, but for some reason it prints a message saying it can't open the device.

**Comment by punkkeks** [comment]
Still an issue!

**Comment by xor-gate** [comment]
Digging up this old issue, probably it was a problem of probing all usb devices and some are not stlink's. Please open a new more detail issue when the problem still remains with latest tools in master and latest stlink firmware (2.27). Thanks!
