### ISSUE TITLE
Semihosting STM32F407 under Win8, gnu...

### ISSUE THREAD

**Issue by mik00** [texane/stlink#227]
**Have YOU made semihosting work on the STM32F407?**
**Please send me a: "Yes!", or a "No, I failed too"**

I'm using a [b]PC (Win8) and the gnu toolchain[/b], [b]cross tools[/b], and the [b]STMF4xx example program[/b] that blinks an LED.   I'm not sure I have everything set up correctly, but I can't find a definitive document describing the current configuration process.  

I can compile, and even debug the semihosted example program, but it simply halts at the first trace statement.  Other people have given up, so I don't want to dig into this unless there is evidence that it works.  

[list][_]Can you point me at the definitive configuration document? 
[_]What are the correct configuration settings?
[*]What is the right ST-LINK firmware?  I upgraded to V2.J19.S0 and it chokes somewhere during the flashing process.  Downgrading to V2.[b]J15[/b].S0 worked OK.  Any confirms on that?  Has the protocol changed in J19?[/list]

If it can be made to work I'll write a guide document.

**Comment by xor-gate** [comment]
Semihosting is not supported by stlink (currently). You have to use OpenOCD for this.

**Comment by Nightwalker-87** [comment]
Old, but still not implemented. Also see recent comment in #147.

**Comment by Nightwalker-87** [comment]
@mik00: I am currently reviewing old leftovers.
Is this resolved with Release v1.3.0? Please verify.

**Comment by mik00** [comment]
Not an issue for me any more thanks.

**Comment by Nightwalker-87** [comment]
So we need somebody else to test...

**Comment by mik00** [comment]
Yes. Sorry, this was six years ago.  I'm working on different hardware in a
different IDE now.

**Comment by Nightwalker-87** [comment]
Who can help to verify this? Any volunteers?
