### ISSUE TITLE
st-term 

### ISSUE THREAD

**Issue by tommyclee042414thu** [texane/stlink#228]
My running ends up with the "stlinky magic not found in sram :(" error. The cause is that the "if (STLINKY_MAGIC == READ_UINT32_LE(sl->q_buf))" check never succeeds. The hard-coded STLINKY_MAGIC value is 0xDEADF00D. My printf() code finds out that the sl->q_buf value on my stm32f207vg production board is 0x09e25030. I replaced 0xDEADF00D with 0x09e25030 and ran again. The same error occurred. 

I am have two questions:

What is the purpose of the st-term utility? Is it for logging the printf() messages from the stm32 board to minicom on stlink designated tty node?

How to make the STLINKY_MAGIC match READ_UINT32_LE(sl->q_buf) happen, in order to run st-term successfully?

**Comment by araasch** [comment]
An example of st-term which works would be great, the code appears to not be currently maintained.

**Comment by xor-gate** [comment]
A more robust way is to use the ARM Semihosting which is fully supported by OpenOCD and libc of https://launchpad.net/gcc-arm-embedded.

**Comment by Nightwalker-87** [comment]
I currently don't see the point why the focus shifted to ARM Semihosting here as the question targeted st-term (now obviously st-util)...

**Comment by Nightwalker-87** [comment]
Closed by #507.
