### ISSUE TITLE
Using LLDB with st-util?

### ISSUE THREAD

**Issue by JetForMe** [texane/stlink#241]
I successfully built code and ran it via gdb on my STM32F4 Discovery board, on OS X 10.9. Thanks for that!

I was hoping to use LLDB, and so I tried the same steps. LLDB uses slightly different instructions (gdb-remote 4242 instead of target extended-remote), but it doesn't seem to have a "load" command.

I wonder if anyone has tried to use LLDB with st-util? How do you do it? Thanks!

**Comment by xor-gate** [comment]
For extended gdb-server you should use OpenOCD (for now).
