### ISSUE TITLE
Cant print variables with gdb

### ISSUE THREAD

**Issue by flaminggoat** [texane/stlink#259]
I have an stm32f429 discovery. Breakpoints work fine hoverver I am unable to access any of the variables. E.g.
```
(gdb)print time
Cannot access memory at address 0x2002fff0
(gdb) info locals
time = <error reading variable time (Cannot access memory at address 0x2002fff0)>
```
Any ideas?

**Comment by xor-gate** [comment]
Should be fixed by now, please test against latest tools in `master` or `v1.2.0` (at time of writing). Feel free to open a new issue if the problem still exists.
