### ISSUE TITLE
auotgen.sh: No such file or directory, failure on build

### ISSUE THREAD

**Issue by RandoSY** [texane/stlink#262]
Attempting to build on Ubuntu 14.10 daily. As far as I know I've installed all the dependencies (autoconf, etc.)

Any ideas?

Thanks!

**Comment by xor-gate** [comment]
Old bug, solved in latest master and you can now use the cmake build system under linux.

**Comment by embhobbb** [comment]
can you please share autogen file with me.
I didn't get that.

**Comment by xor-gate** [comment]
No, autogen is deprecated since v1.3.0. See https://github.com/texane/stlink/blob/bf1b81b93077ae1c3eadc5d5accc47293ff7f375/ChangeLog.md#v130.
