### ISSUE TITLE
Multiple chips on the same JTAG bus

### ISSUE THREAD

**Issue by rost0031** [texane/stlink#265]
So I'm developing a board that uses multiple STM32Fxx chips.  Keil has an option with their debugger to specify which of the chips on the JTAG bus you want to connect to and flash/debug/etc.  Is this possible with this tool or if not, is this in the works?

**Comment by xor-gate** [comment]
Previously and in the future stlink tools will not support multiple chained devices as mentioned by @lanserge as this tool is based on stlink protocol reverse engineered work and no protocol specification is available for the stlink programmers. Sorry!
