### ISSUE TITLE
fail to compile on win8 using gcc 

### ISSUE THREAD

**Issue by enjoydiy** [texane/stlink#286]
I am trying to compile on whindows using mingw msys, I fail. There are some hints:
./configure: line 4359: syntax error near unexpected token `USB,'
./configure: line 4359: `PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0,,'

I have installed libusb-1.0.

pkg-config --libs libusb-1.0
-LC:/MinGW/msys/1.0/local/lib -lusb-1.0

**Comment by xor-gate** [comment]
This is an old issue, you should test with latest master. When it still fails please open a new issue. Thanks!
