### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by mikepurvis** [texane/stlink#306]
Current release is over a year old. Consider tagging 1.0.1 or 1.1?

**Comment by texane** [comment]
good idea, done

2015-04-02 20:24 GMT+02:00 Mike Purvis <notifications@github.com>:

**Comment by xor-gate** [comment]
Hi guys, I have just tagged 1.2.0 and added the first ChangeLog.md with the notable changes. Closing this now :=). Thanks for reporting @mikepurvis.
