### ISSUE TITLE
Flash data gets corrupted after verify passed (STM32F429I-Discovery)

### ISSUE THREAD

**Issue by ambrop72** [texane/stlink#308]
When I flash my program to the board using st-flash, the flashing will succeeds with verification passing, but after some time or power cycling, some data in a particular part becomes corrupted. I have checked this by reading back data using st-flash and diff'ing the hexdumps - I can see a few bytes different.

**When the chip is flashed using OpenOCD, the data does not evaporate and is flashed reliably.**

**Comment by xor-gate** [comment]
I'm digging up old issues, this should be fixed by PR #371. Please open a new detailed issue when this problem still occurs with latest stlink tools from master and latest stlink firmware (2.27).
