### ISSUE TITLE
FreeRTOS support

### ISSUE THREAD

**Issue by gduteil** [texane/stlink#317]
Hi,

First of all thank you this great tool.

I'm working on a FreeRTOS support (https://github.com/gduteil/stlink)
There are probably some issues, but it starts to work.

It has been tested on STM32F407 with FreeRTOS 8.2.0.

If people are interested in testing it, please let me know how it goes.

Thanks !

Guizmo

**Comment by nvdl** [comment]
I can test it. Will soon order one STM32 Discovery board.

**Comment by xor-gate** [comment]
This feature request is almost two years old and never merged back. I will now close this due to inactivity. Feel free to open a new issue or a pull request to contribute. Thanks in advance!

**Comment by Nightwalker-87** [comment]
Is there _any_ interest for this in the community?
Please give some feedback.

**Comment by Nightwalker-87** [comment]
Since no further demand has been registered for this feature, this ticket is now finally closed.
