### ISSUE TITLE
STM32F301x

### ISSUE THREAD

**Issue by duro80** [texane/stlink#319]
Please add support to STM32F301x MCU. In the current version, the chipID (0x439) and coreID (0x2ba01477) detect correct, but flashing fails:

WARN src/stlink-common.c: unknown coreid 2ba01477, page erase failed
ERROR src/stlink-common.c: Failed to erase_flash_page(0x8000000) == -1
stlink_fwrite_flash() == -1

**Comment by xor-gate** [comment]
@duro80 could you test with latest tools in master branch?

**Comment by duro80** [comment]
It works. Thank You.

**Comment by xor-gate** [comment]
Thanks for testing!
