### ISSUE TITLE
Flash utility very slow on OS X 10.6

### ISSUE THREAD

**Issue by EtiennePhillips** [texane/stlink#32]
Hi All

THANKYOU for providing this utility. It's really appreciated!

I'm running Snow Leopard, and am finding the flash utility (last week's version) really slow when writing to STM32F4Discovery board. I'm playing with the audio example, which generates a 1MB binary, which takes about 20mins to download to the device. When using the ST-Link utility (the official ST one) on Windows, it downloads in 1-2 mins.

Is there a compilation flag, or something I'm missing that would speed things up?

Thanks!
Etienne

**Comment by xor-gate** [comment]
As it is 4 years ago some activity was going on in this issue and things have changed over time i'm closing this. Please test with `v1.2.0` or `master`. Feel free to open a new issue when there are still problems. Thank you for your contribution!
