### ISSUE TITLE
STM32F7 Support

### ISSUE THREAD

**Issue by Darwin2011** [texane/stlink#337]
Hello, 

I hope to know whether stlink can support STM32F7 discovery board?
I will get such board soon so I ask the question in advance.

Thanks
Best Regards

**Comment by mlu** [comment]
We added support for the STMF7 Discovery board a few weeks ago and I have used it to both flash the board from st-flash and debug and also flash from gdb using st-util.

**Comment by Darwin2011** [comment]
Thanks, Mlu!
