### ISSUE TITLE
STM32F469I-DISCO how to program MCU external 128-Mbit Quad-SPI NOR Flash

### ISSUE THREAD

**Issue by belzt** [texane/stlink#355]
This tool will program the internal Flash of the mcu (STM32F469NIH6) without trouble, but slow. How can I program the 128-Mbit Quad-SPI NOR Flash on the board? Its a Micron N25q128A13EF840F, connected directly to the MCU (PF6-PF11)?

**Comment by xor-gate** [comment]
This is not related to the stlink tools project, you should write a small SPI NOR flash loader application firmware which can feed data through the native usb of the STM32F4 and then write it to the on-board flash.
