### ISSUE TITLE
program running on ST-LINKv2 instead of stm32 board

### ISSUE THREAD

**Issue by daiyoko** [texane/stlink#361]
Hi, i use a USB stick like ST-LINK v2 and connect to my little STM32F103C8T6 board. And i can successfully flash the sample blinky program, but it seems the program is running on ST-LINK v2??? Instead of the little board.

ST-LINK v2 i'm using is like this one =>
http://www.electrodragon.com/product/st-link-v2-programmer-for-stm8-stm32/

STM32 board i'm using is like this one =>
http://www.electrodragon.com/product/stm32-mini-dev-board-stm32f103c8t6-arm/

After deploy the program, the little light on ST-LINK v2 is flashing/blink but i expect is the LED on STM32 is blinking???

The program i use is default from Eclipse C Project sample.

**Comment by Nightwalker-87** [comment]
@daiyoko: I am currently reviewing old issues as one of the new maintainers of this project. I know this is an old issue, but why was this closed without further notice? Any helpful solution found? Is there anything to improve? Please give feedback to us.
