### ISSUE TITLE
Could you help to support STM32L072CZ for stink V2?

### ISSUE THREAD

**Issue by andy-y-li** [texane/stlink#387]
Could you help to support STM32L072CZ for stink V2?
For XP, it has support.
  On mac, it is fail at "WLOG("unknown chip id! %#x\n", chip_id);":
unknown chip id! xxxxxx447

**Comment by gluedig** [comment]
you might try with my repo as i added support for L073RZ device which is pretty simmilar

**Comment by xor-gate** [comment]
@gluedig could you prepare a reviewable pull request against master?

**Comment by xor-gate** [comment]
@gluedig is the `STM32L072CZ` now supported with latest changes? @andy-y-li could you test the tooling from `master` branch?

**Comment by gluedig** [comment]
@xor-gate i have no way of verifying on L072 as i have no such device, only L073
quick glance at datasheet indicates L072 is L073 minus LCD driver

**Comment by xor-gate** [comment]
I understand, so basicly the current stlink tool flash loader should work out of the box.

**Comment by Nightwalker-87** [comment]
Please verify with Release v1.6.0.

**Comment by Nightwalker-87** [comment]
@andy-y-li: Please verify if this has been resolved in Release v1.2.0 and v1.3.0.
