### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by plaudis** [texane/stlink#403]
~/stlink > ./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:12: installing './compile'
configure.ac:14: installing './config.guess'
configure.ac:14: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
Makefile.am:54: warning: variable 'st_probe_LDADD' is defined but no program or
Makefile.am:54: library has 'st_probe' as canonical name (possible typo)
autoreconf: Leaving directory `.'

~/stlink > ./configure

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/plaudis/Desktop/Real-Time Embedded/stlink':
configure: error: C compiler cannot create executables
See `config.log' for more details

~/stlink > make
make: *** No targets specified and no makefile found.  Stop.

[config.log.txt](https://github.com/texane/stlink/files/243967/config.log.txt)

does not build properly on linux mint 17. Am i missing anything or is it just not supposed to work?

**Comment by xor-gate** [comment]
Yes this was unseen by the merge of st-probe into st-info. @texane fixed this in #c9fe110. You should try again with latest master and close if it works (or use cmake).
