### ISSUE TITLE
fixes for ST USB host library

### ISSUE THREAD

**Issue by byly** [texane/stlink#42]
Hi!

I'm writing bluetooth usb driver based upon ST USB host library and btstack (http://code.google.com/p/btstack). I've fixed a couple of bugs in ST USB host library (after which my driver became operational).

I want to submit these bug fixes somewhere but I'm not very sure where to. I see this project includes ST code and has refs to ST devteam, so I figured you may now better. Sorry if I'm abusing your issue tracker.

**Comment by xor-gate** [comment]
Unrelated to stlink project.
