### ISSUE TITLE
STM32F100 development kit does not work since change to libusb

### ISSUE THREAD

**Issue by galexander1** [texane/stlink#423]
Using current master (f4991d80), I found that my old STM32F100 development kit does not work.  It gets a libusb error reading the target voltage, and then all further libusb calls fail.

I believe the relevant change to stlink is the addition of libusb as an alternative to sg.  I had previously (2011) used the sg driver, and it did not provide the target voltage function so it did not have this problem.  But with the new libusb driver, it does attempt the unsupported command.

**Comment by galexander1** [comment]
The call to that crashes my STM32F100 is happening from gdb-server, because it outputs the voltage for informational purposes (ILOG).  In other places, the target voltaeg is determined only for certain kinds of boards where that is necessary, and it does not cause this problem.

Pull request 424 fixes this issue for me.

And thank you for adding the libusb support!  Now that I'm past this issue, it works way more reliably than the sg mode interface did in the past.

**Comment by xor-gate** [comment]
Which hardware target do you use ? The STM32VLDiscovery with STM32F100RBT6B ?
http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-discovery-kits/stm32vldiscovery.html

**Comment by galexander1** [comment]
Yes, that's the one.  Though my board is old (2011), so I don't know if there are different revisions since then.

**Comment by galexander1** [comment]
It is this chipid: STLINK_CHIPID_STM32_F1_VL_MEDIUM_LOW = 0x420,

**Comment by xor-gate** [comment]
I'm currently don't have a test setup, in the upcoming weeks I would be able to verify. When removing reading of target voltage for gdb-server would not change the behaviour of the gdb interface. But i'm wondering how many people rely on it currently. In my opinion the gdb-server should not do this.
