### ISSUE TITLE
"[!] send_recv" error message is a little cryptic

### ISSUE THREAD

**Issue by galexander1** [texane/stlink#425]
To diagnose a recent problem (#423), I found screens full of "[!] send_recv", which was not meaningful to me - I could not even be certain it was an error message.  Pull request forthcoming.

**Comment by galexander1** [comment]
I made pull request #426 to address this issue.  When the send_recv() fails, now it outputs the libusb error name and what it was trying to do (send request/read reply) when the failure happened.  And when the caller notices send_recv() failed, it also outputs the STLINK_... command name that it was attempting.  Makes it particularly easy to unambiguously diagnose when one stage in stlink access causes future requests to fail.

**Comment by xor-gate** [comment]
Hi @galexander1 looks very good to me. @texane could you also review the PR #426? I would like to merge this.

**Comment by texane** [comment]
sorry for delay, but looks good to me too

2016-06-05 20:37 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
Good, so my "silent" merge effort is not lost :=)

**Comment by texane** [comment]
Of course it is not :)

2016-06-05 20:45 GMT+02:00 Jerry Jacobs <notifications@github.com>:
