### ISSUE TITLE
ARM Semihosting support

### ISSUE THREAD

**Issue by xor-gate** [texane/stlink#429]
Hi all,

I have started a experiment to implement ARM Semihosting I/O facility inside stlink here:
https://github.com/xor-gate/stlink/tree/semihosting

It is currently hacked and only one semihosting call works and then the CPU hangs. But its a good start.
I currently have no plan when this will be merged as the gdb-server stub is very hard-coded.

Read more about ARM semihosting:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471m/pge1358787045051.html

Any contributions are welcome!

**Comment by Nightwalker-87** [comment]
Addressed by #454 and #455.
