### ISSUE TITLE
Discussion: Autotools will be deprecated in v1.3.0

### ISSUE THREAD

**Issue by xor-gate** [texane/stlink#431]
As per `2.0.0` I will deprecate the use of autotools (autoconf, automake). As it is not as cross-platform minded as CMake. And I am unable to maintain two build systems. Installing on windows autotools is a pain and I want to create IDE or console projects. The reasons why I only want to support CMake:
- No obsecure m4-macro system, and have a decent programming language (no wrapped shell commands) for the build system
  - Loops
  - Conditionals
  - Variables
- Easy to maintain different targets with different compiler flags
- Generate files (from templates) in a cross-platform fashion (not using sed,grep awk etc)
- Builtin testing facility (CTest)
- Builtin packaging facility (CPack)
- Multiple output generators (Make, Xcode (OSX), Visual Studio)

One current use-case is:
Generate a `version.h` from `version.h.in` template and use it to notify users which version they run. Completely automatic created from git tags or `version.txt` file.

**Comment by texane** [comment]
I agree with you. So lets deprecate autotools, unless there is a strong
argument about keeping it.

2016-06-07 19:24 GMT+02:00 Jerry Jacobs <notifications@github.com>:

**Comment by xor-gate** [comment]
Thank you @texane for the feedback, there are tons of other nice features why we should stick with cmake. I will keep things posted here when I need some discussion.

**Comment by rikvdh** [comment]
👍  for CMake, I see no point in keeping autotools as well.

**Comment by xor-gate** [comment]
Fixed by PR #434
