### ISSUE TITLE
st-util version information

### ISSUE THREAD

**Issue by SL-RU** [texane/stlink#470]
Please add --version attribute to st-util & st-flash(and other utils). It is useful information and it easy to implement.

**Comment by xor-gate** [comment]
Thats a good idea as I have a now the version information available in the `<stlink/version.h>` header. Pull request PR #469 is still pending review by others. I will add this with new release v1.3.0.

Thanks for the suggestion!

**Comment by xor-gate** [comment]
I have added it, first the `cmake-fixes` branch needs to be merged before the `--version` feature can be used.

**Comment by SL-RU** [comment]
Yoy! Thanks ^^
