### ISSUE TITLE
Make the requirement about "pandoc" is configurable

### ISSUE THREAD

**Issue by gerryqd** [texane/stlink#479]
Hi,

I am using stlink for several months,  I buit it on Cygwin, but after recent upgrades, I cannot able to build it out successfully. Seems that "pandoc" is required to generate the manpages.

Is it possilbe to make it configurable? For example, "cmake MANPAGES=NONE".

Or if it cannot find the "pandoc", it will not generate the manpges, just as it checks for the "GTK". 

Thanks & Regards,
Gerry

**Comment by xor-gate** [comment]
You are right, currently the Release target will not generate the man-pages with pandoc. The Debug target will. I will patch it so we have cmake option like: `STLINK_ENABLE_DOC` (like nanomsg does: https://github.com/nanomsg/nanomsg/blob/master/CMakeLists.txt#L90-L97)

**Comment by gerryqd** [comment]
Seems that it is fixed, right?

I built it on debian 8.6,  though I have not install pandoc, it can be built out successfully.

I also verified this on Cygwin.

**Comment by texane** [comment]
Yes. The fix is not clean, but it now works without pandoc installed.

2016-09-29 15:10 GMT+02:00 gerryqd <notifications@github.com>:

**Comment by xor-gate** [comment]
@gerryqd could you try on latest master?

**Comment by xor-gate** [comment]
Related to #487, fixed in commit https://github.com/texane/stlink/commit/68b0f3bddc3c4aaffe34caa6a3201029edd8ad56.
