### ISSUE TITLE
st-flash on stlink v1 broken

### ISSUE THREAD

**Issue by dflogeras** [texane/stlink#480]
I am using a stm32-discovery (Old STM32F0 kit, stlink v1) as a programmer for a homebrew F405 board.  OS is Gentoo Linux.

I'm running into a problem that after updating to master today.  I can use "st-util -1" to connect to the board, and verify it sees the target correctly.  However, if I try to program the target using st-flash write my.bin 0x8000000, it fails with:
[!] send_recv read reply failed: LIBUSB_ERROR_PIPE
[!] send_recv STLINK_JTAG_DRIVE_NRST
[!] send_recv send request failed: LIBUSB_ERROR_PIPE
[!] send_recv STLINK_DEBUG_RESETSYS
[!] send_recv send request failed: LIBUSB_ERROR_PIPE
[!] send_recv STLINK_GET_VERSION
2016-09-21T11:12:59 INFO /home/dave/stlink/src/common.c: Loading device parameters....
[!] send_recv send request failed: LIBUSB_ERROR_PIPE
[!] send_recv STLINK_DEBUG_READCOREID
2016-09-21T11:12:59 ERROR /home/dave/stlink/src/common.c: Failed to read core_id
[!] send_recv send request failed: LIBUSB_ERROR_PIPE
[!] send_recv STLINK_JTAG_READDEBUG_32BIT
2016-09-21T11:12:59 WARN /home/dave/stlink/src/common.c: unknown chip id! 0x612010

After this, I cannot connect with st-util either.  Only unplugging from the USB and re-plugging it gets back communication.  I bisected, and commit ac43cfdfef8f3dc8d95cd31548b4786646f81c4c seems to be the culprit.  I verified that on master, if I remove the offending line added in that commit, it works as expected again.

**Comment by xor-gate** [comment]
Yes this is legit, OpenOCD does the same:

https://github.com/ntfreak/openocd/blob/master/src/jtag/drivers/stlink_usb.c#L827-L831
https://github.com/ntfreak/openocd/blob/master/src/jtag/drivers/stlink_usb.c#L1011-L1027
