### ISSUE TITLE
Erroneous deletion st-term utility

### ISSUE THREAD

**Issue by arhiv6** [texane/stlink#507]
In version 1.3.0 "Removal of undocumented st-term utility", but this utility has documentations:
https://github.com/texane/stlink/commit/3c28cf15a79b50d273fa8147b93eb7c09c770f0b

**Comment by xor-gate** [comment]
Thats right, but it needs some custom firmware to be usefull. It has been deprecated in favor of [ARM semihosting](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471l/pge1358787056080.html).

**Comment by Nightwalker-87** [comment]
`st-term` was removed with commit 3fd0f099782506532198473b24f643a3f68d5ff9.
