### ISSUE TITLE
Compile under Ubuntu

### ISSUE THREAD

**Issue by gorynch** [texane/stlink#519]
Hi
I'm trying to compile stlink under Ubuntu 15.04
I have C maker, gcc, libusb, libusb-dev.
Type in Terminal
`$ git clone git://github.com/texane/stlink.git`
and 

> 
> $ make release
> [RELEASE]
> Makefile:27: recipe for target 'release' failed
> make: *** [release] Error 2

There are a lot of manuals how to install stlink, BUT all of them using **autogen.sh**. In my case there is no such file.
Any idea?

**Comment by xor-gate** [comment]
Try running `make clean && make release` this probably due to missing `build/Release` folder and CMake files. Did you git cloned the latest version from `master` branch?

**Comment by vijayandra** [comment]
When STLINK connected with Ubuntu, softreset from firmware does not work. Debugged very long to find issue but now seems Linux/Qstlink combination is issue.

**Comment by julienrhodes** [comment]
I had to run `cmake .` to make the build files prior to make.

**Comment by xor-gate** [comment]
Then you are building **inside the source folder**, I recommend:

```
mkdir build && cd build && cmake .. && make
```

**Comment by xor-gate** [comment]
I'm closing this, as it is inside the [doc/compiling.md](https://github.com/texane/stlink/blob/master/doc/compiling.md) documentation.
