### ISSUE TITLE
Linux mint 18 64-bit  installation issue, With latest git code issue in code:debuild -uc -us

### ISSUE THREAD

**Issue by vallab** [texane/stlink#520]
I have followed all the steps in https://github.com/texane/stlink/blob/master/doc/compiling.md
installed all the required dependencies. please guide me how to compile  it fails after `debuild -uc -us`

Output:

```
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package libstlink
dpkg-buildpackage: source version 1.2.1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Andrew 'Necromant' Andrianov <andrew@ncrmnt.org>
 dpkg-source --before-build stlink
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by xor-gate** [comment]
Hi @vallab I have edited your content of the issue. If you read the error message correctly you need to install debhelper (https://packages.debian.org/jessie/debhelper). 

It should be added to the documentation (for debian based distros).

**Comment by vallab** [comment]
Thanks xor-gate it compiled

**Comment by xor-gate** [comment]
Great, I need to add this to the documentation before v1.3.0 (reopening so I dont forget).
