### ISSUE TITLE
NUCLEO STM32L476RG works fine

### ISSUE THREAD

**Issue by robbymckilliam** [texane/stlink#521]
This issue is just to report that we've been successfully using stlink with the [NUCLEO STM32L476RG](http://www.st.com/en/evaluation-tools/nucleo-l476rg.html) for a few months now. You might wish to update the list in the README.md

**Comment by xor-gate** [comment]
Thanks for reporting, I will add this before release v1.3.0.

**Comment by xor-gate** [comment]
Thank you!
