### ISSUE TITLE
Compile under Ubuntu 16.04

### ISSUE THREAD

**Issue by df8508** [texane/stlink#529]
I use Ubuntu 16.04
I am new to linux and i am starting to work on it recently, 
I have my stlink/v2 work on windows. but it not works on linux.
My problem is following:

i can not find the
```
./autogen.sh
./configure inside the directory .
```
i followed this: Compile under Ubuntu #519 
but it cannot help, 
but my commend 'make' works

however, due to some webpage , the st-util, st-flash and st-info are locate in under the main directory but located in different one, is it correct ?
thanks 

![screenshot from 2016-12-15 18-17-26](https://cloud.githubusercontent.com/assets/12265214/21220598/9c02ff6c-c2f4-11e6-8b83-f280fb468583.png)
 
- [X] Programmer/board type: Stlink/v2
- [ ] Programmer firmware version: STSW-LINK007 2.27.15
- [X] Operating system: Linux 
- [X] Stlink tools version and/or git commit hash: v1.2.0-155/gecc-31f7
- [X] Stlink commandline tool name: e.g `st-info`, `st-flash`, `st-util`

**-- Edited issue by @xorgate**

**Comment by xor-gate** [comment]
It works as expected, problem due some missing documentation or read incorrectly:

* Where the final executables are placed
* How to install the build

Have you read this document (which is linked from the mainpage README.md)?:
https://github.com/texane/stlink/blob/master/doc/compiling.md#build-from-sources

At the end of the section there is a note how to install into `$HOME` or root `/`

**Comment by xor-gate** [comment]
Did you managed to find and get the executables running?

**Comment by df8508** [comment]
> Did you managed to find and get the executables running?

Yes.thanks you a lot ~

**Comment by xor-gate** [comment]
Thank you for your feedback. Have fun!
