### ISSUE TITLE
Am i Configure right for the gdb configure --host=x86_64-linux-gnu?

### ISSUE THREAD

**Issue by df8508** [texane/stlink#544]
**NOTICE: The issue may be closed without notice when not enough information is provided!**

Thank you for giving feedback to the stlink project. Take some time to fill out
 check boxes with a X in the following items so developers and other people can try to
 to find out what is going on. And add/remove what is appropriate to your problem.

When submitting a feature request, try to reuse the list and add/remove what is appropriate.
 Place a `X` between the brackets `[X]` to mark the list item.

- [X] Programmer/board type: Stlink/v2
- [Ｘ] Programmer firmware version: e.g Crypto
- [X] Operating system: e.g Linux
- [X] Stlink tools version and/or git commit hash: 
- [X] Stlink commandline tool name: e.g `st-info`, `st-flash`, `st-util`
- [X] Target chip (and optional board): e.g STM32F205TB

A as-detailed description possible of the problem with debug output when available.
i run command as arm-none-eabi-gdb main.elf
Output:
My Question is as title: 
and i type configure it shows
 configure --host=x86_64-linux-gnu --target=arm-none-eabi
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/lib/arm-none-eabi/share/gdb

because i saw this 
remember, you need to run an ARM gdb, not an x86 gdb)

Am i on the right track?
thx
```
OUTPUT/ERROR of the commandline tool(s)
```

Expected/description:
`short description of the expected value`

Thank you,
The stlink project maintainers

**Comment by xor-gate** [comment]
I'm sorry but this has nothing todo with the texane/stlink project about building a own GDB binary. You should better use linaro or arm gnu toolchain.

https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
https://www.linaro.org/downloads/
