### ISSUE TITLE
Build error: cannot find -lstlink

### ISSUE THREAD

**Issue by thehans** [texane/stlink#547]
- [X] Programmer/board type: Stlink/v2
- [X] Programmer firmware version: unknown
- [X] Operating system: Linux Mint 17.3
- [X] Stlink tools version and/or git commit hash: eea16d762979fcfc28937c784c480c8346247a3a
- [X] Stlink commandline tool name: n/a
- [X] Target chip (and optional board): e.g STM32F103

When attempting to compile from source, the build exits with error "cannot find -lstlink"

Attached is the output of running ```make release``` from the top directory after a fresh git clone
[build.txt](https://github.com/texane/stlink/files/737960/build.txt)

**Comment by xor-gate** [comment]
Nice catch, I'm not 100% sure why this happens but on Debian 8 it works (or worked) fine. I will fix this in v1.3.1.

**Comment by xor-gate** [comment]
Related to issue #551 and probably fixed with PR #552.

**Comment by thehans** [comment]
works now, thanks.
