### ISSUE TITLE
STM32F7 devices failed to program at low-voltages.

### ISSUE THREAD

**Issue by zulusw** [texane/stlink#566]
The "parallelism" bits get set correctly but there wasn't an F7 low-voltage algo available.
So it ends up trying to perform a 32-bits flash programming with PSIZE fields set to 0x00.

I have a fix for it if. If interested I can submit a pull request.

**Comment by xor-gate** [comment]
Hi @zulusw, thats a pitty. Indeed when flash is in low power mode it needs a different algo. With stlink2 and stlink2-1 we are able to detect the voltage and select a different algo. Feel free to submit a PR.

**Comment by xor-gate** [comment]
Ref PR #567
