### ISSUE TITLE
Do OpenOCD and ST-Util both can give the GDB service? What is the different? 

### ISSUE THREAD

**Issue by zhubeilife** [texane/stlink#580]
- [X ] Programmer/board type: Stlink/v
- [ X] Programmer firmware version: e.g STSW-LINK007 2.27.15
- [ X] Operating system: Linux
- [ X] Stlink commandline tool name: e.g `st-info`, `st-flash`, `st-util`
- [ X] Target chip (and optional board): e.g STM32F103RB

Do OpenOCD and ST-Util both can give the GDB service? What is the different? 

Thanks!

**Comment by xor-gate** [comment]
OpenOCD and st-util both implement a gdb server which are used to program and debug the stm32 firmware application. Those are completely two different projects. OpenOCD implements also the driver to control the stlink programmer. But it also has an TCL scripting language integrated which st-util doesn't have.
