### ISSUE TITLE
Compile fails on Mac OS 10.6 x86_64

### ISSUE THREAD

**Issue by LawrenceLeung** [texane/stlink#60]
I'm getting this link error when building stlink on mac os 10.6:

ld: in ../libstlink.a, archive has no table of contents for architecture x86_64

Any ideas?  I have a reasonably recent XCode installed that is known to build for x86_64 just fine.

Thanks
-Lawrence

**Comment by xor-gate** [comment]
Old issue, please try with latest master. When the problem remains please reopen or open a new issue.
