### ISSUE TITLE
How to get the serial logs through stlink in Linux?

### ISSUE THREAD

**Issue by binary-nerd** [texane/stlink#606]
Programmer/board type : stlink/v2
Target Chip : Nucleo F091RC
OS: Linux (Ubuntu 16.04)

### With STMF091RC Evaluation board and stlinkV2-onboard :
When i connected the stlinkV2-onboard of STMF091RC evaluation board to my PC, i see a serial port with name `/dev/ttyACM0`. I was able to use this to see the `printf` logs of my mbed code.

### With stlinkV2 and STMF091RC Micro controller :
With stlink/V2 and F091RC mic contoller, I do not see any serial port created when I connect it to my PC. How can i see the serial logs in this case?

**Comment by xor-gate** [comment]
There are two different kind of programmers. Stlinkv2 and Stlinkv2/1 which is mostly on board of nucleo/discovery. Those development kits have extra functionality and standalone programmers don't support that. You should try to consider ARM semihosting printf or ARM ITM port 0 printf and is easy to google.
