### ISSUE TITLE
make release error

### ISSUE THREAD

**Issue by unlimited123az** [texane/stlink#625]
I saw a similar issue,but I have installed cmake,libusb,gcc
I try to run "make release" ,however
[RELEASE]
make[1]: *** No targets specified and no makefile found.  Stop.
Makefile:27: recipe for target 'release' failed
make: *** [release] Error 2

I have no idea.

I tried "make debug"
It stops halfway.
I tried again,and then
[DEBUG]
make[1]: *** No targets specified and no makefile found.  Stop.
Makefile:23: recipe for target 'debug' failed
make: *** [debug] Error 2

**Comment by xor-gate** [comment]
First run `make clean` after cmake fails then run `make` again.

**Comment by unlimited123az** [comment]
Many thanks，it works well！

**Comment by unlimited123az** [comment]
One more question............
I plug in my stm32 board,but 
/dev/stlink dose not exist,I can not execute 
st-util -1

**Comment by xor-gate** [comment]
`/dev/stlink` is only created by a custom udev rule. Probably you should run `st-util` without arguments.

**Comment by unlimited123az** [comment]
There is no st-uil 
bash:st-uil:command not found

**Comment by xor-gate** [comment]
The `st-util` is there where it is build, see https://github.com/texane/stlink/blob/master/doc/compiling.md.

**Comment by unlimited123az** [comment]
Many thanks,
I can keep on learning stm32 now.
