### ISSUE TITLE
clang 4.0.0+ can not compile version 1.4.0

### ISSUE THREAD

**Issue by blacklion** [texane/stlink#628]
clang 4.0.0 or newer can not compile 1.4.0 release because it uses
```
add_cflag_if_supported("-Wall")
add_cflag_if_supported("-Wextra")
add_cflag_if_supported("-Werror")
```
in `CFlags.cmake`, and later add integer to string literal (in logging code), which is warning for clang. Build log is attached,

[build.txt](https://github.com/texane/stlink/files/1239240/build.txt)

**Comment by xor-gate** [comment]
This is the same error as build with ninja and GCC in PR #624. We need to fix this in the logging module.

**Comment by slyshykO** [comment]
we can use strrchr ( [](http://en.cppreference.com/w/c/string/byte/strrchr) ) for extracting the base name.
Another problem is the dir separator on windows depends on compiler and cmake generator. And can be both '\' and '/' .

**Comment by xor-gate** [comment]
Yes for windows you can have multiple path separators (cygwin/mingw/native).

**Comment by slyshykO** [comment]
Is it still a bug?

**Comment by blacklion** [comment]
I've checked very last "master" (95b6e03ed0c0ee40256a33f04eedf702005a9d8b), and it build flawlessly with clang 5.0.0 on 64-bit system.
Thank you!

**Comment by xor-gate** [comment]
Thanks all for being proactive.
