### ISSUE TITLE
stm32f102c8t6 doesn't flash

### ISSUE THREAD

**Issue by z80** [texane/stlink#63]
Hello!

I tried STM32L-DISCOVERY based ST-LINK v2 to flash STM32F102C8T6. It worked perfectly on Windows with Atolic GDB server. So I'm sure schematic is OK. I experimented using "./gdbserver/st-util" and "./flash/st-flash" to write and read flash. It looks like it can read flash data but neither write nor erase operations could be done. I tried the following combinations.

"st-util" with "arm-none-eabi-gdb" combination: "load ./target.elf" and "load ./target.hex" process starts but never ends. According to ST-LINK's LED blinks I may know some interaction takes place. But it takes forever.

"st-flash" utility recognizes chip, it's memory and flash size. But neither "write" nor "erase" commands ever finish. I tried "read" command and it's managed to get some file from flash.

It looks like none of write operations (gdb's load, st-flash's write or erase) have any impact on flash content as far as my test firmware is still inside after all experiments.

By the way, both tools (st-flash and st-util) flash well STM32L-DISCOVERY's built-in STM32L microcontroller.

I hope this information helps.

**Comment by Nightwalker-87** [comment]
To me this topic does not seem to have been resolved... Any update on this?
@z80: Please retry with the latest Release v1.6.0 as this issue is referenced by an open ticket. Thx.

**Comment by Nightwalker-87** [comment]
@z80: I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0? Please verify.

**Comment by Nightwalker-87** [comment]
No patch necessary as modification is user-specific and has therefore not been submitted.
