### ISSUE TITLE
On 64-bit system libs installed to /usr/lib instead of /usr/lib64.

### ISSUE THREAD

**Issue by Vascom** [texane/stlink#633]
In Fedora linux 32-bit and 64-bit packages can be installed simultaneously. 32-bit libs to /usr/lib and 64-bit libs to /usr/lib64.
Please add to cmake configuration support for LIB_INSTALL_DIR parameter.

**Comment by xor-gate** [comment]
Yes this is a bug, feel free to submit a PR.
