### ISSUE TITLE
redefine CMAKE_ABSOLUTE_DESTINATION_FILES to DESTDIR/root

### ISSUE THREAD

**Issue by ponyatov** [texane/stlink#645]
Required to be able to redefine `CMAKE_ABSOLUTE_DESTINATION_FILES`
for sed preprocessing before installing this files into root system itself

It should be some prefix variable like `CMAKE_ABSOLUTE_PREFIX ?= /`
to use some temp directory

PS: 
I'm forked to ponyatov/stlink and going to do
`git checkout tags/1.4.0 -b ponyatov_140`
is it be possible to send a pull request from `ponyatov_140` branch?

**Comment by ponyatov** [comment]
make DESTDIR= install works without any changes

**Comment by xor-gate** [comment]
Great, thanks for reporting back.
