### ISSUE TITLE
build and run without root access

### ISSUE THREAD

**Issue by ponyatov** [texane/stlink#646]
I'm trying to build development framework can be used at user level without root access.

Now I have problems with stlink build: 

1. default build wants /usr/local/ but I'm going to avoid any system-wide changes

```
CWD = $(CURDIR)        ## /home/user/STM32
TOOL = $(CWD)/tools    ## cross toolchain and utils will be here
STLINK_CFG = -DCMAKE_INSTALL_PREFIX=/stlink
$(STLINK): stlink/README_ponyatov.md /usr/include/libusb-1.0/libusb.h
	cd stlink ; $(MAKE) clean ;\
	$(MAKE) DESTDIR=$(TMP) CMAKEFLAGS="$(STLINK_CFG)" install &&\
	cp -r $(TMP)/stlink/* $(TOOL)/ 
```
2. Running `$(TOOL)/bin/st-util` gives me error with unfound .so libraries, so I want to build all statically,

Or maybe it will be better just redefine `LD_LIBRARY_PATH` ? I'm going to build fresh `arm-none-eabi-binutils|gcc` from scratch, is it bad to build it statically too ?

**Comment by Vascom** [comment]
All static builds are bad. 
Usually root not need for build, only for install. You can just skip install step and run stlink from build directory.

**Comment by ponyatov** [comment]
Install works as I need (with some Linux limitation: unprivileged user can not control udev rules).
Also, I found a solution: define `LD_LIBRARY_PATH` and `PATH` in a user profile.

Whats wrong with static build?

**Comment by xor-gate** [comment]
We had before a static build (and probably it still is for windows), there is nothing wrong with that. But somebody needed stlink as a shared library.

**Comment by Nightwalker-87** [comment]
Please verify if the problem still exists in Release v1.6.0.

**Comment by Nightwalker-87** [comment]
@ponyatov: What is the current state of this issue? Which release version did you use? Can you please provide more details on your build system.

**Comment by ponyatov** [comment]
I have no experience with this a lot of time ago, sorry.
