### ISSUE TITLE
Read Out Protection is not detected by st-flash and results in an error and no board detection

### ISSUE THREAD

**Issue by Invincibl-e** [texane/stlink#649]
Today, I use a ST-Link v2 to download to my board ( STM32F103C8 ). The st-flash always report error and can't identify my board. Then, I try to it on Windows ( ST-Link Utility ). The ST-Link Utility report `Cannot read memory! Disable Read Out Protection and retry.` [Discuss]( https://community.st.com/thread/8710 ).

Finally, go to Target > Option Bytes > Read Out Protection and select `Disable` option. Take it back to OS X, it can be work.

I found some similar problem in this issues, which may help you solve the problem.

So, what is the `Read Out Protection`?

**Comment by xor-gate** [comment]
Read out protection is a feature of the microcontroller to prevent 3th party and malicious users reading out your application from flash memory. So they are not able to copy your products firmware.

**Comment by Nightwalker-87** [comment]
Feedback closes #649.
