### ISSUE TITLE
USB command documentation

### ISSUE THREAD

**Issue by szoshi** [texane/stlink#652]
Hello,

I am writing a simple flash utility for a basic stm8 from scratch and would like to use the STLINK hardware for the same. I could find the basic SWIM protocol but no documentation for the raw USB commands used. Is there a resource out there which documents the USB interface for the programmer or was it reverse engineered to develop this code? If yes, is there a way I coud gain access to the information?

Regards,
Shailesh

**Comment by xor-gate** [comment]
No the STM32 programming protocol is reversed engineered and is released under non-disclosed-agreement (NDA). The predecessor of `texane/stlink` is based on the original reverse engineer work of [The "Capt'ns Missing Link" Authors - capitanio.org/mlink](https://capitanio.org/mlink/). A closed issue already exists about the STM8 support at https://github.com/texane/stlink/issues/154.
