### ISSUE TITLE
Cannot find st-util in clone folder

### ISSUE THREAD

**Issue by SuperCiocia** [texane/stlink#653]
Hello,

I have followed your instructions to clone and make the folder but I cannot find the <code>st-util</code> executable, essential for further work.

All the files I see in the cloned directory are:
![capture](https://user-images.githubusercontent.com/33633189/32739984-6290fe36-c899-11e7-9f09-ba578c2d2757.PNG)

The steps that I have taken till here are:

1) <code> git clone https://github.com/texane/stlink.git </code>

2) <code> cd stlink </code>

3) <code> make </code>

4) <code> cd build/Release && make install DESTDIR=_install

**Comment by Vascom** [comment]
You can find it in `src/gdbserver/st-util`

**Comment by Nightwalker-87** [comment]
No bug. Issue has been solved.
