### ISSUE TITLE
not work mac os x binary on snow leopad

### ISSUE THREAD

**Issue by yamori813** [texane/stlink#677]
I try to stlink-1.3.0-macosx-amd64 binary on snow leopad(10.6.8) but now work.

bash-3.2$ ./st-flash 
Illegal instruction

I seem newer Xcode make not compatible Mach-O binary for snow leopad.

Regards

**Comment by xor-gate** [comment]
On such an old Mac OS X version you have to compile your own version https://github.com/texane/stlink/blob/master/doc/compiling.md. Probably you first need to compile or get a binary version of libusb as that is the only dependency. Sorry!

**Comment by yamori813** [comment]
thanks for your comment. current code can't compile on gcc4. Because of for(int i;;) is error on gcc4.

**Comment by xor-gate** [comment]
variable declaration inside loops is supported since C99, not sure if GCC 4 supports it. you would be better of to get yourself a raspberry pi and run stlink on there.

**Comment by yamori813** [comment]
I make pr. https://github.com/texane/stlink/pull/678
