### ISSUE TITLE
Please add png icon

### ISSUE THREAD

**Issue by Vascom** [texane/stlink#684]
Can you add icon in PNG format for use in desktop file? Now stlink menu entry has blank icon and it is not good.
It should be 512x512 picture.

**Comment by xor-gate** [comment]
Feel free to submit a PR, I only run OS X desktop.

**Comment by Vascom** [comment]
And it has no any icon on OS X?

**Comment by xor-gate** [comment]
Its just an CLI application, no GUI

**Comment by joede** [comment]
I've added PR #708 to make the first step. I don't know CMake, so there is work needed.
