### ISSUE TITLE
Static executable for Linux

### ISSUE THREAD

**Issue by Zensey** [texane/stlink#689]
Is there any way to make a static executable ?

**Comment by Vascom** [comment]
Why you need it?

**Comment by Zensey** [comment]
ok.
may be I should consider delivery by means of packaging.

**Comment by slyshykO** [comment]
I think that is possible make a static build for non-GUI part of stlink.
The only need is to add a static build for libusb and make necessary
changes in CMakeLists.txt. For now, it is impossible.

чт, 22 мар. 2018 г., 9:23 Vasiliy Glazov <notifications@github.com>:

**Comment by xor-gate** [comment]
Under linux there is no reason to have a static executable. You should get it from the distro repository or compile and install yourself. There is always a never ending struggle with static and non-static builds. Distro's don't like to build static (takes up more disk space). 

The static magic is only happening for OS X and Windows builds (for now). See

https://github.com/texane/stlink/blob/master/CMakeLists.txt#L132-L135
https://github.com/texane/stlink/blob/master/CMakeLists.txt#L169

**Comment by Nightwalker-87** [comment]
Feedback closes #689.
