### ISSUE TITLE
32l_lcd example, GCC ICE, __attribute__((naked))

### ISSUE THREAD

**Issue by rogerdahl** [texane/stlink#69]
The 32l_lcd example is currently not working. This is noted in the code, which skips the GPIO configuration that would make it possible to use the LCD.

The following line occurs in the code: // fixme: GPIO_Init raises a bug in some gcc toolchains

And indeed, if the GPIO_Init lines are uncommented, attempting to compile gives an internal compiler error (ICE) in GCC:

main.c: In function 'main':
main.c:164:12: internal compiler error: in expand_expr_addr_expr_1, at expr.c:6927
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make: *** [main.o] Error 1

I have done some searching online and have found that, though this is an ICE in GCC, it is not really a problem with GCC. It is triggered by invalid use of the __attribute__((naked)) keyword. The fix that GCC implementors are considering would simply change this from an ICE to a compile error. The basic issue appears to be that __attribute__((naked)) is intended for pure assembly functions, and not for the way it is used in the definition of main() in the 32l_lcd example. Because __attribute__((naked)) causes the compiler to not set up a stack frame for the function, almost any C code would have the potential of triggering the ICE.

So, I did a test, and removed  __attribute__((naked)) from the definition of main(). This "fixed" the ICE issue, but I was unable to start the resulting ELF file on the Discovery board.

Why is __attribute__((naked)) needed on main(), and how can the project be repaired so that the attribute is not needed?

Thank you,

Roger Dahl

**Comment by Nightwalker-87** [comment]
Review: Does not seem to be related to the stlink-project.
