### ISSUE TITLE
Add/merge support for STM32L4R9 

### ISSUE THREAD

**Issue by photomattmills** [texane/stlink#694]
I have a fork with this working [here](https://github.com/texane/stlink/compare/master...photomattmills:master), I don't know if it needs further cleanup to meet standards, happy to do so if needed.

- [x] Programmer/board type: Stlink/v2-onboard
- [x] Programmer firmware version: e.g STSW-LINK007 2.27.15
- [x] Operating system: Mac OS X 
- [x] Target chip (and optional board): e.g STM32L4R9AI (STM32L4R9-DISCO)

**Comment by xor-gate** [comment]
Hi @photomattmills, please submit the PR then we can have a look. Thanks for your effort.

**Comment by photomattmills** [comment]
Done. Thanks!

**Comment by xor-gate** [comment]
Thank you!
