### ISSUE TITLE
Installation issue under linux

### ISSUE THREAD

**Issue by cedricboudinet** [texane/stlink#700]
Hello,
stlink installation under Linux (Debian 9) is broken since modifications for #695: libstlink.so (and others) installs in /usr/local/lib/lib instead of /usr/local/lib
It seems that the error comes from these instructions:
 if(IS_DIRECTORY CMAKE_LIBRARY_PATH)
 else()
    set(CMAKE_LIBRARY_PATH "lib")
 endif()
If I change it to 
 if(IS_DIRECTORY CMAKE_LIBRARY_PATH)
 else()
    set(CMAKE_LIBRARY_PATH "")
 endif()
then it works again.
I can create a PR if you want, but I cannot test the modification under other OS.

**Comment by Vascom** [comment]
I can confirm.
Also hardcode path to "lib" breake x86_64 with /usr/lib64 folder.

**Comment by xor-gate** [comment]
Hi guys, I agree with your both. We must find a working solution for all cases (with less cmake code).

**Comment by slyshykO** [comment]
In my defence, I would say that I encounter a situation when CMAKE_LIBRARY_PATH is a list of paths. That broke all install command completely.
In my opinion, we should remove CMAKE_LIBRARY_PATH  from all install commands.

**Comment by Cheng-SG** [comment]
I encountered the same issue

**Comment by Vascom** [comment]
@Cheng-SG please try #701 fix
