### ISSUE TITLE
make[1]: *** No targets specified and no makefile found.

### ISSUE THREAD

**Issue by PirikitoOreo** [texane/stlink#717]
Hello, my os is Linux Mint 18.3
I executed next commands for instaling STLINK on my PC:
**sudo apt-get install git
sudo apt-get install autoconf
sudo apt-get install libusb-1.0-0-dev
git clone https://github.com/texane/stlink stlink.git
cd stlink.git/
make release**

After typing next command: make release
I've got next error:
**[RELEASE]
make[1]: *** No targets specified and no makefile found. Stop.
Makefile:27: recipe for target 'release' failed
make: *** [release] Error 2**

I also have read instruction https://github.com/texane/stlink/blob/master/doc/compiling.md, but i'm just started with Linux and I dont understand what i have to do.
Could help me with instalation step by step please?

**Comment by xor-gate** [comment]
Please provide details.

**Comment by PirikitoOreo** [comment]
Hello, after typing next command: make release
I've got next error:
[RELEASE]
make[1]: *** No targets specified and no makefile found. Stop.
Makefile:27: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by xor-gate** [comment]
Provide more details please. As the first post in this thread suggests.
You should remove the build folder probably due to non-installed depencies the Makefile is not generated under build/Releas/Makefile. I advice you to read https://github.com/texane/stlink/blob/master/doc/compiling.md.

**Comment by PirikitoOreo** [comment]
Thank you for your reply, but iI think I'm completely lost.
Could you show me commands that i have to un please.

**Comment by xor-gate** [comment]
Start reading https://github.com/texane/stlink/blob/master/doc/compiling.md.

**Comment by xor-gate** [comment]
You are not answering my questions and providing details, so I can not help you.

**Comment by xor-gate** [comment]
I think you forgot to install cmake.

**Comment by PirikitoOreo** [comment]
After installing **build-essential**, commands **make release** and **make debug** worked well.
What sould I do next?
Thanks

**Comment by xor-gate** [comment]
You should build a debian package with `make package`, and install the package with `dpkg -i *.deb`.

**Comment by PirikitoOreo** [comment]
Thank you for your reply. I executed your commands an I think everything is OK.
Bellow I post the output:
**~/stlink.git $ make package
[PACKAGE] Release
[ 23%] Built target stlink-static
[ 46%] Built target stlink
[ 56%] Built target st-flash
[ 63%] Built target st-info
[ 76%] Built target st-util
[ 83%] Built target sg
[ 90%] Built target usb
[100%] Built target flash
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: stlink
CPack: - Install project: stlink
CPack: Create package
CPack: - package: /home/usr/stlink.git/build/Release/stlink-1.4.0-39-g6db0fc2-amd64.deb generated.**

**~/stlink.git $ cd /home/usr/stlink.git/build/Release/
usr@usr-desktop ~/stlink.git/build/Release $ sudo dpkg -i *.deb
Selecting previously unselected package stlink.
(Reading database ... 311484 files and directories currently installed.)
Preparing to unpack stlink-1.4.0-39-g6db0fc2-amd64.deb ...
Unpacking stlink (1.4.0-39-g6db0fc2) ...
Setting up stlink (1.4.0-39-g6db0fc2) ...
Processing triggers for man-db (2.7.5-1) ...**

**Comment by PirikitoOreo** [comment]
I was trying to upload test firmware to my stm32f103C8T6 using stlink-v2 and system workbench ide, but without success. I don't understand where is a problem. How can I check if my stlink-v2 is correctly installed?

**Comment by xor-gate** [comment]
I would like to help you, but re-read what your are writing. Trying to understand what your problem is, i'm missing details (logfile, what did you type etc).

**Comment by PirikitoOreo** [comment]
I would like to show you logfile, is it possible to find/generate it?

**Comment by lyakh** [comment]
I had the same problem as the OP. What fixed it is running "make clean" before "make". Looks like some files got committed to git that shouldn't be there?

**Comment by Nightwalker-87** [comment]
Closing #717 as useful feedback has been given. Please open a new ticket if necessary.
