### ISSUE TITLE
st-util hangs at "Listening at *:4242"

### ISSUE THREAD

**Issue by arithemetica** [texane/stlink#723]
**NOTICE: The issue may be closed without notice when not enough information is provided!**

Thank you for giving feedback to the stlink project. Take some time to fill out
 check boxes with a X in the following items so developers and other people can try to
 to find out what is going on. And add/remove what is appropriate to your problem.

When submitting a feature request, try to reuse the list and add/remove what is appropriate.
 Place a `X` between the brackets `[X]` to mark the list item.

- [X] Programmer/board type: Stlink/v2-1
- [ ] Programmer firmware version: don't know where to find it..
- [X] Operating system: e.g Mac OS Sierra
- [X] Stlink tools version and/or git commit hash: v1.4.0
- [X] Stlink commandline tool name: st-util
- [X] Target chip (and optional board): STM32 Nucleo F429ZI

A as-detailed description possible of the problem with debug output when available.

Input:
$ st-util

Output:
st-util 1.4.0
2018-07-11T15:30:15 INFO common.c: Loading device parameters....
2018-07-11T15:30:15 INFO common.c: Device connected is: F42x and F43x device, id 0x20016419
2018-07-11T15:30:15 INFO common.c: SRAM size: 0x40000 bytes (256 KiB), Flash: 0x200000 bytes (2048 KiB) in pages of 16384 bytes
2018-07-11T15:30:15 INFO gdb-server.c: Chip ID is 00000419, Core ID is  2ba01477.
2018-07-11T15:30:15 INFO gdb-server.c: Listening at *:4242...

that's all

```
OUTPUT/ERROR of the commandline tool(s)

it just keep listening..
```

Expected/description:

I expect to see something link "(gdb) " instead of this, but it is hanging there forever.

Thank you,
The stlink project maintainers

**Comment by xor-gate** [comment]
It doesn't hang it just waits for you connect with `arm-none-eabi-gdb`:

```
$ arm-none-eabi-gdb
(gdb) target remote 127.0.0.1:4242
```

Read GDB documentation here https://sourceware.org/gdb/onlinedocs/gdb/Connecting.html
