### ISSUE TITLE
README.md build steps are not valid!

### ISSUE THREAD

**Issue by aspirine92** [texane/stlink#725]
Since tag 1.3.0 and later there is no autogen script and no st-util target!

Please update the README.md file with the latest changes!

**Comment by xor-gate** [comment]
Feel free to make a PR, opensource is contribution based and you get full credits.

**Comment by xor-gate** [comment]
I had a search through the repository files and could not find any occurences of autogen. I have removed it long time ago and it is possible in releases after 1.3.0 some documentation is incorrect.

**Comment by Nightwalker-87** [comment]
As of Release v1.3.0 there is no reference to `autogen` in README.md.
