### ISSUE TITLE
Murata can't be programmed during sleep mode?

### ISSUE THREAD

**Issue by silardg** [texane/stlink#734]
- [ X] Programmer/board type: Stlink/v2-onboard
- [ X] Operating system: Linux=
- [X ] Target chip (and optional board):=cmwx1zzabz-091 murata

I have put my murata chip into sleep and can't get it to flash.
Output on boot0 tied to gnd (pulldown 10k)
![screenshot_20180830_163404](https://user-images.githubusercontent.com/10872257/44860218-03858300-ac76-11e8-9f3a-6931ac75089a.png)

Output on boot0 tied to vcc (pullup 10k)
![screenshot_20180830_164237](https://user-images.githubusercontent.com/10872257/44860240-0f714500-ac76-11e8-8de1-7947d865f2ad.png)

I have tried:
- timing the reset button to get it to program: did not work
- boot0 to vcc
- different stlink
- different cable for stlink
- checked cables from stlink to board

Thanks!

**Comment by xor-gate** [comment]
Hi @silardg, thanks for reporting. As far as I know stlink is not ready to support sleep mode debugging/programming. It requires some effort. In the meantime I point you to the more complete OpenOCD which should work.

**Comment by silardg** [comment]
Thanks for the reply. The chip wasn't properly soldered on.

**Comment by Nightwalker-87** [comment]
Does not seem related to the st-link project anyway...
