### ISSUE TITLE
MacBook pro 2016- STM32L4 can't find device

### ISSUE THREAD

**Issue by pdedman** [texane/stlink#742]
I have a MacBook pro 2016 (4 thunderbolts) running macOS High Sierra connected to a STM32L475 and st-util returns the following error: 

"WARN usb.c: Couldn't find any ST-Link/V2 devices"

The device is connected through a thunderbolt-USB A adaptor and receiving power. Has anyone tested on the most recent MacBook?

Thanks!

**Comment by xor-gate** [comment]
Which programmer do you use, onboard or external stlink?

**Comment by pdedman** [comment]
I am not sure. I followed the directions in: https://github.com/texane/stlink/issues/499 running st-util from my MacBook terminal. However, I tried connecting my STM32 to my raspberry pi and it won't even detect it.

**Comment by pdedman** [comment]
Ah. Sorry. Tried a third USB cable and it works now.

**Comment by pdedman** [comment]
Found this https://github.com/texane/stlink/issues/736 and tried a third cable like OP. Works fine now. Thank you.

**Comment by xor-gate** [comment]
Those problems are always hard to find. Thanks for updating the issue. Good luck!
