### ISSUE TITLE
Switching between JTAG/SWD mode

### ISSUE THREAD

**Issue by mj1226** [texane/stlink#743]
I am wonder, why I cant find anywhere, how to switch between JTAG/SWD modes. Please can you explain it me? I will use primarily original ST ST-LINK/V2 programmer and I would need to use both modes. Thanks.

**Comment by xor-gate** [comment]
The stlink programmers only use SWD (SWO,SWD,SWCLK pins). JTAG is not supported. You should get a different programmer interface (e.g Olimex JTAG) and using OpenOCD application. Or an segger J-Link: https://www.segger.com/products/debug-probes/j-link/.
