### ISSUE TITLE
libusb driver for windows

### ISSUE THREAD

**Issue by mj1226** [texane/stlink#744]
Stlink-V2, 
- [X] Operating system: Windows 7
- [X] Stlink tools version v1.3.0
- [x] Target chip STM32F103

As it is stated, the stlink is depended on the libusb driver. Firstly I had driver installed with the ST STM32 ST-LINK UTILIY but it didn’t worked properly with yours stlink utils. After this driver uninstalling and intalling the libusb-win32 from: https://sourceforge.net/projects/libusb-win32/ , I received problem code 48 in Device Manager (The software for this device has been blocked from starting because it is known to have problems with Windows. Contact the hardware vendor for a new driver.)
Please is it possible to use your stlink tools on Windows 7 and how I can install the needed device driver? Thanks, Milan.

$ st-info --probe
Found 0 stlink programmers
2018-10-30T17:29:12 WARN C:\Users\Jerry\Desktop\stlink-master\src\usb.c: failed to get libusb device descriptor

**Comment by xor-gate** [comment]
It should not be necessary to install libusb as it is staticly linked.

Windows 10 AMD64
```
C:\Users\id0000\Downloads\stlink-1.3.0-win64\bin>st-info.exe --probe
Found 1 stlink programmers
```

The development board is an STM32L496 discovery kit which was not supported on v1.3.0. I'm not sure what causes the problems.

**Comment by mj1226** [comment]
The my posted program response it had reported immediately after the stlink installation. Because there was an uninstalled device STM32 ST-Link in the device manager, I tried to install the ST STM32 ST-LINK UTILITY, which installed also ST native driver. Then the st-info --probe gave exactly the same short prompt as in your case. But I had no HW for connecting to programmer and I also thought, that the program response should be longer. Then I had received a Blue Pill with STM32F103C8T6 and I connected it to the programmer. But commands as st-flash read ... or st-info --probe gave some errors and it didn't worked. Then I tried to install the libusb-win32 driver, after it the st-info --probe gave detailed output but with zero values and st-flash read ... reported some long message with errors. Then I removed all stlink drivers and tried to install only the libusb-win32 driver. But it give me the message in the device manager 48 and the st-info --probe didn't find the programmer.

Please if you open the device manager, can you see the driver for the connected ST-Link programmer? And what you have on the related tab Driver in the first line (intermediary)? I have now libusb-win32 there. 

I downloaded the stlink-1.3.0-win64.zip file, unzipped it to the c:/opt/stlink directory and set PATH to its bin directory. I didn't find any more detailed description of installation in Windows. May be there is needed to move lib file somewhere or make another settings?

Thank You, Milan.

**Comment by Nightwalker-87** [comment]
@mj1226: Please verify if the problem still exists in Release v1.6.0 and also ensure that libusb is v1.0.19 or later.

**Comment by Nightwalker-87** [comment]
@slyshykO: Old and/or incompatible libusb version probably?

**Comment by slyshykO** [comment]
> 
> 
> @slyshykO: Old and/or incompatible libusb version probably?

I don't know. Never use libusb-driver for windows. Always use st-link drivers  provided by ST

**Comment by Nightwalker-87** [comment]
@mj1226: I don't think that we can ensure compatibility and provide support for libusb drivers from other software projects. I propose you to verify your hardware is ok and then to retry with a clean build of Release v1.3.0. If that does not solve the problem, proceed with Release v1.3.1. Please open a new ticket then. Closing this this old ticket now, as useful advice has been provided.
