### ISSUE TITLE
troff man pages show wrong dash style for options

### ISSUE THREAD

**Issue by reox** [texane/stlink#746]
Some options in the man pages of `st-info` and partially `st-util` use a single dash instead of a double dash.
For example, `st-info` has the option `--probe` (shown in the examples section
correctly), but the man pages says `-probe`.
When using `st-info -probe`, the tool just exists with a status code of 0.
The man page of `st-util` contains in the description hints to the options
`-listen_port` and `-stlinkv1` which seems to be also replaced by the double
dash variants.

The options are correctly written in the markdown files, but it seems that pandoc does this automatically. I'm no expert at pandoc but it seems it is this package causing it: https://pandoc.org/MANUAL.html#typography

See also Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914103

**Comment by xor-gate** [comment]
Hi @reox,

I have looked into the generation and seems we did not as pandoc expectation. Could you have a look?

<img width="558" alt="screenshot 2018-11-19 at 19 10 02" src="https://user-images.githubusercontent.com/1050166/48726144-bc80ab80-ec2e-11e8-9240-9fc37dcd5755.png">

There is only a very small issue left where something is not bold.

Let me know.

Kind regards,
Jerry

**Comment by reox** [comment]
@xor-gate yep, that looks good! thank you!

**Comment by xor-gate** [comment]
Fixed in latest master now! Thanks for reporting.
