### ISSUE TITLE
Add support for mass erasing second bank on STM32F10x_XL

### ISSUE THREAD

**Issue by bmellstrom** [texane/stlink#767]
I added support for bank 2 on STM32F10x_XL a few years ago but apparently forgot to implement mass erase for it. The commit below fixes that:

https://github.com/bmellstrom/stlink/commit/52129373227dcaf58f89a0b0d7eef3311f8815e7

Shall I open a pull request?

**Comment by xor-gate** [comment]
Please do 😃

**Comment by xor-gate** [comment]
Thanks!
