### ISSUE TITLE
How do we control NRST pin via GDB?

### ISSUE THREAD

**Issue by ceremcem** [texane/stlink#774]
I'm successfully using st-link for STM32F103 and STM32F407 devices. I noticed no need for NRST pin to be able to fully manage a debug session. [`reload`](https://github.com/aktos-io/mcu-debug/blob/3a45c0972969850e968c604ee4d46a0e4a3e87aa/gdb-init#L30-L61)ing code just works (including restarting the MCU). 

However, when I use STM32F030 device, it turns out it's necessary to generate a NRST signal in order to properly restart the MCU. As an example, I created a blinker example which generates a square wave on a pin and load the code to the MCU. Pin does not alter its state. When I manually connect the NRST pin to the GND and release, pin starts generating square wave as intended. 

I connected a logic analyzer to the NRST pin of the debugger hardware. Neither loading the code directly (`st-flash write`) nor loading via GDB generates NRST pulse. However, `st-flash erase` or `st-flash --reset write` generates this NRST pulse, which means `stlink` is capable of sending NRST pulse command to the debugger hardware. 

According to [the document](https://www.st.com/content/ccc/resource/technical/document/application_note/91/66/2d/8c/f9/b5/47/55/DM00089834.pdf/files/DM00089834.pdf/jcr:content/translations/en.DM00089834.pdf), Any reset should generate a negative pulse on NRST pin:

![image](https://user-images.githubusercontent.com/6639874/53758396-bc02dc80-3ece-11e9-9644-b229f8d41257.png)

This must mean that when [I trigger a software reset with `kill` within GDB](https://github.com/texane/stlink#resetting-the-chip-from-gdb), I must see a negative pulse on the NRST pin via logic analyzer. However, it doesn't appear to do so. 

# Question 

Question comes to the point: How do we generate `NRST` pulse via gdb command in order to properly restart the MCU?

**Comment by xor-gate** [comment]
This is a very good question, I'm not sure when the jtag reset function is called from GDB. The lowlevel programmer command is implemented here https://github.com/texane/stlink/blob/30de1b30e7a96974ae764d0508c151eadb1addd1/src/usb.c#L395-L414. For the GDB server in st-util it is located here https://github.com/texane/stlink/blob/b9c315d990abfde3008a917e767c63d2c1c1ddf2/src/gdbserver/gdb-server.c#L1234-L1250. So probably sending a `jtag_reset` command through the gdb `monitor` should work (interactive shell `monitor jtag_reset`).

**Comment by ceremcem** [comment]
`monitor jtag_reset` works as expected. Thanks.
