### ISSUE TITLE
«on_trans_done» undeclared

### ISSUE THREAD

**Issue by legath** [texane/stlink#78]
in branch master. 
last hash "d2c78b96e05291d21e363c09840cd3cfac1c8961"
OS: Linux Mint 12

**Comment by Nightwalker-87** [comment]
@legath: which version of the stlink toolset did you use? Please also retry with a newer libusb version if possible.

**Comment by Nightwalker-87** [comment]
> Can you test with #if not defined (LIBUSB_CALL) #define LIBUSB_CALL #endif?

This proposed fix has been submitted via commit fc85ba71f1bd1eeebbc36e69bc5d667c812784b3 afterwards.
As it reads from the code, one can safely assume that these missing lines caused the mentioned compilation error and their addition resolve this issue.

**Comment by legath** [comment]
It was so long ago. I have moved to manjaro linux and becomes use openocd and jlink gdb server

**Comment by Nightwalker-87** [comment]
@legath: It's ok now as it is, don't worry about it.
