### ISSUE TITLE
stty: /dev/ttyUSB0: No such file or directory

### ISSUE THREAD

**Issue by sevgicorumlu** [texane/stlink#806]
sudo ./test_stm32f0.sh 

stty: /dev/ttyUSB0: No such file or directory
./test_stm32f0.sh: 6: ./test_stm32f0.sh: st-flash: not found
./test_stm32f0.sh: 7: ./test_stm32f0.sh: cannot open /dev/ttyUSB0: No such file
0a1
> c8a71edd37b496ed9f1c763b86f1614b24215280e6d4c48b6cdf477f9f92af6c (what it means)

**Comment by Nightwalker-87** [comment]
@sevgicorumlu: Can you shortly describe what action solved this issue for you? Thx in advance.

**Comment by Nightwalker-87** [comment]
It appears that `st-flash` is either not installed or the binary-path is missing in the $PATH system variable. No USB device is detected at address `/dev/ttyUSB0`. As the content of the custom script remains unknown, no further help can be provided.
