### ISSUE TITLE
PKG_CHECK_MODULES USB unexpected token

### ISSUE THREAD

**Issue by zansibar** [texane/stlink#83]
I installed this a month ago on OSX and it went fine, I had to reinstall osx and now I am running into problems. 

./configure: line 4781: syntax error near unexpected token `USB,'
./configure: line 4781:`PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0.0,,'

I already installed libusb:

$ pkg-config --libs libusb
-L/usr/local/lib -lusb 

$ pkg-config --libs libusb-1.0
-L/usr/local/lib -lusb-1.0  

if I comment out the line 4781 from configure which causes the problem then it creates the make file but the makefile doesn't Include or link correctly. 

I can compile it by adding -lusb-1.0 to the gcc command (also added -I/usr/local/include/libusb to the makefile)

gcc  -g -O2    -o st-util gdbserver/st_util-gdb-remote.o gdbserver/st_util-gdb-server.o mingw/st_util-mingw.o libstlink.a -lusb-1.0

Any ideas why I don't have this USB token?
What should it be?

**Comment by xor-gate** [comment]
Closing this issue as the roots date back into 2012. Now things have been working as expected using autoconf or cmake. Reopen when issue still remains.

**Comment by sguillia** [comment]
Hello,

I've still got the same problem. None of the above answers got it to work for me.

Running on Debian 8.5

```
checking for doxygen... /usr/bin/doxygen
./configure: line 13518: syntax error near unexpected token `libusb,'
./configure: line 13518: `        PKG_CHECK_MODULES(libusb, libusb, HAVE_LIBUSB=1, HAVE_LIBUSB=0)'
```

Has any solution been found since 2012 ?
Thank you

**Comment by xor-gate** [comment]
@sguillia please do not recycle this old issue for new problems (this is label as original reported on os/macosx). Autoconf is going to be deprecated in the upcoming time. So only CMake build system is supported. See pull request #434 and issue #431.

**Comment by Nightwalker-87** [comment]
This issue is now permanently closed.
