### ISSUE TITLE
udev: Unable to receive message

### ISSUE THREAD

**Issue by lpvm** [texane/stlink#838]
- [x] Programmer/board type: Stlink/v2
- [x] Programmer firmware version: e.g STSW-LINK007 2.27.15
- [x] Operating system: Linux
- [x] Stlink tools version and/or git commit hash: 05b5739642b
- [x] Stlink commandline tool name: e.g `st-info`, `st-flash`, `st-util`
- [x] Target chip (and optional board): STM32F103

I don't know if I've understood the instructions correctly.
What I did was:
git clone the project
from the root dir of it: make release, and then make debug
also copied the udev rules
lsusb shows
`Bus 009 Device 004: ID 0483:3748 STMicroelectronics ST-LINK/V2`

```
# ls -l /dev/bus/usb/009/004 
crw-rw-rw- 1 root root 189, 1027 out  9 23:39 /dev/bus/usb/009/004

```
What I did then was to cd to build/Release and issue some commands:
```
# ./st-info --version
v1.5.1-43-g05b5739
```
```
# ./st-info --flash
no db file to read /run/udev/data/+usb:9-4:1.0: No such file or directory
unable to receive message
no db file to read /run/udev/data/+usb:9-4:1.0: No such file or directory
unable to receive message
0x0

```
```
# ./st-info --probe
no db file to read /run/udev/data/+usb:9-4:1.0: No such file or directory
unable to receive message
no db file to read /run/udev/data/+usb:9-4:1.0: No such file or directory
unable to receive message
Found 1 stlink programmers
 serial: 303030303030303030303031
openocd: "\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x31"
  flash: 0 (pagesize: 0)
   sram: 0
 chipid: 0x0000
  descr: unknown device
```

So, there seems that there is some problem.
I double checked the cables between the STM32F103 and the ST-Link. There's a red led light up on the STM32F103.
Am I doing something wrong?  This is just my first time dealing with microcontrollers.

Thanks.

**Comment by Nightwalker-87** [comment]
This looks like as if udev rules and/or permissions are not set properly.
Please consult our tutorial at `/doc/tutorial.md` and follow the instructions "HowTo - Verify if udev rules are set correctly" to solve this problem that very likely derived from a false configuration on the local system.
