### ISSUE TITLE
On Raspberry PI 3 and 4, OS native raspbian, with gcc 8.3.0 buid script fails at the configuration stage.

### ISSUE THREAD

**Issue by T-Duke** [texane/stlink#848]
**NOTICE: The issue may be closed without notice when not enough information is provided!**

Thank you for giving feedback to the stlink project. Take some time to fill out
 check boxes with a X in the following items so developers and other people can try to
 to find out what is going on. And add/remove what is appropriate to your problem.

When submitting a feature request, try to reuse the list and add/remove what is appropriate.
 Place a `X` between the brackets `[X]` to mark the list item.

- [ ] Programmer/board type: e.g Stlink/v1, Stlink/v2, Stlink/v2-onboard
- [ ] Programmer firmware version: e.g STSW-LINK007 2.27.15
- [ ] Operating system: e.g Linux, Mac OS X, Windows (with specific version)
- [ ] Stlink tools version and/or git commit hash: e.g v1.1.0/git-c722056
- [ ] Stlink commandline tool name: e.g `st-info`, `st-flash`, `st-util`
- [ ] Target chip (and optional board): e.g STM32F402VG (STM32Fxxx Discovery)

A as-detailed description possible of the problem with debug output when available.

Output:

```
OUTPUT/ERROR of the commandline tool(s)
```

Expected/description:
`short description of the expected value`

Thank you,
The stlink project maintainers

**Comment by T-Duke** [comment]
This test fails:

C SOURCE FILE Test C_SUPPORTS_WMISSING_VARIABLE_DECLARATIONS
C_SUPPORTS_WSHORTEN_64_TO_32

**Comment by T-Duke** [comment]
Solved.

As always, it needs careful reading of docs. Development headers libusb-1.0-0-dev MUST be installed as it is described in build docs.
Thanks to developers for this project!

**Comment by Nightwalker-87** [comment]
Resolved by author.
