### ISSUE TITLE
32l_lcd example works but output is garbled

### ISSUE THREAD

**Issue by fuzxxl** [texane/stlink#89]
I've just tried to use the example in the directory examples/32l_lcd on a STM32l discovery board. So far it works just fine, but the output appears garbled—at the end of the display some blocks light up (that probably shouldn't). Single stepping shows, that the display is blanked just fine, the conversion logic is probably broken.

Here are some pictures:

* http://dl.dropbox.com/u/1869832/STM32l-discover-ON.jpg
* http://dl.dropbox.com/u/1869832/STM32l-discover-OFF.jpg

**Comment by xor-gate** [comment]
Unrelated to stlink project.
