### ISSUE TITLE
Problems with debugging after "load" command

### ISSUE THREAD

**Issue by kjellhar** [texane/stlink#95]
Hi, I've been using st-util with the STM32F4Discovery, and I have encountered a weird problem that I guess would mostly go by unnoticed. I am using the latest Yagarto toolchain on a Mac with OSX Lion.

I have compiled a simple blink led program using Chibios, which works fine, but when I do the following, the debugging will not work.

1. Start the st-util
2. start arm-none-eabi-gdbtui
3. gdb>  tar rem :4242
4. gdb>  file ch.elf
5. gdb>  load
6. gdb>  cont

At this point, the program will be running, but it is in a deadlock in the idle task. My guess is that something has happened during the "load" that changes some of the interrupts or something. The reason for thinking this is that if I reset the card, the led will blink as it should, and if I skip sep #5  (assuming I already loaded the program), it will debug correctly.

If one of the developer wants to look into this, I will be more than happy to provide the ELF file I'm using, as well as any additional information.

**Comment by elvisfox** [comment]
You could also use 'monitor jtag_reset' command just before 'start' or 'run' to perform hardware reset your taget MCU.

**Comment by xor-gate** [comment]
Feel free to open a new issue when the problem still remains with `v1.2.0` or `master`. Thanks all for your contributions.
